version: "3"

services:

  redis:
    image: redis:alpine
    networks:
      - frontend
    deploy:
      placement:
        constraints:
          - "node.role == worker"

  db:
    image: postgres:15-alpine
    networks:
      - backend
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    deploy:
      placement:
        constraints:
          - "node.role == worker"

  fronted-ovoz:
    image: feruzjon/ovoz:latest
    networks:
      - frontend
    ports:
      - "5000:80"
    deploy:
      replicas: 2
      placement:
        constraints:
          - "node.role == worker"

  fronted-natija:
    image: feruzjon/natija:latest
    networks:
      - backend
    ports:
      - "5001:80"
    deploy:
      placement:
        constraints:
          - "node.role == worker"

  backend:
    image: feruzjon/backend:latest
    networks:
      - backend
      - frontend
    deploy:
      replicas: 2
      placement:
        constraints:
          - "node.role == worker"



networks:
    frontend:
    backend:

volumes:
  db-data:
