version: '3'
services:
  wordpress:
    image: wordpress:latest
    container_name: wordpress
    environment:
      - WORDPRESS_DB_NAME=wordpress
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
    depends_on:
      - db
    ports:
        - 80:80
  db:
    image: mariadb:10.6.4-focal
    container_name: db
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=somewordpress 
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpresscat 
      - MYSQL_DATABASE=wordpress
    ports:
        - 3306:3306
volumes:
  db_data:
    driver: local 
