version: "3"
services:
  db:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=12345
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
    ports: 
      - "3306:3306"
    networks:
      - my-network
    volumes:
      - db_data:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'
  wordpress:
    image: wordpress
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
      - WORDPRESS_DB_NAME=wordpress
    ports: 
      - "80:80"
    networks:
      - my-network
    depends_on:
      - db
networks:
  my-network:
    driver: bridge
volumes:
  db_data:
    driver: local
